version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: patient-service-db
    environment:
      POSTGRES_DB: patientdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5000:5433"
    volumes:
      - patient-service-db:/var/lib/postgresql/data
    networks:
      - internal

volumes:
  patient-service-db:

networks:
  internal:
    driver: bridge